encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "pedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/edit", views.edit, name='edit'),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms


from . import util
from markdown2 import markdown
from random import choice

class EditPageForm(forms.Form):
    title_form = forms.CharField(widget=forms.TextInput({"class":"form-control font-weight-bold"}))
    info_form = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control", 'placeholder': "Use markdown syntax"}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki(request, title):
    info = util.get_entry(title)
    if info is not None:
        return render(request, "encyclopedia/wiki.html", {
            'title': title,
            'info': markdown(info)
        })
    else:
        return render(request, "encyclopedia/error.html", {
            'message': f"Wiki page for {title} not found",
            'info': f"but you can <a href={reverse('pedia:new')}>create</a> new"
             },
             status=404)



def search(request):
    list_files = util.list_entries()
    q = request.GET.get('q', '')

    # Try to find a file with that name and redirect to wiki pages if found
    if q in list_files:
        return HttpResponseRedirect(reverse("pedia:wiki", kwargs={'title':q}))

    # looking for files with a keyword
    search_results = [file for file in list_files if q.lower() in file.lower()]
    return render(request, "encyclopedia/search.html", {
        'results': search_results,
        'search_query': q
    })


def random(request):
    page = choice(util.list_entries())
    return HttpResponseRedirect(reverse("pedia:wiki", kwargs={'title':page}))


def edit(request, title):
    if request.method == 'POST':
        form = EditPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['info_form']
            util.save_entry(title, content) # Save to file
            return HttpResponseRedirect(reverse("pedia:wiki", kwargs={'title':title}))
        else:
            return render(request, "encyclopedia/edit.html", {
                'title': title,
                'form': form
            })

    info_md = util.get_entry(title)
    if info_md is None:
        # Redirect to create new page
        return HttpResponseRedirect(reverse("pedia:new"))

    # create and fill form fields. Disable to edit title form.
    form = EditPageForm(initial={'title_form': title, 'info_form': info_md})
    form.fields['title_form'].widget.attrs['readonly'] = True
    return render(request, "encyclopedia/edit.html", {
        'title': title,
        'form': form
    })


def new(request):
    if request.method == 'POST':
        form = EditPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['info_form']
            title = form.cleaned_data['title_form']
            if title not in util.list_entries():
                util.save_entry(title, content) # Save to file
                return HttpResponseRedirect(reverse("pedia:wiki", kwargs={'title':title}))
            else:
                return render(request, "encyclopedia/error.html", {
                    'message': f"Page <b>{title}</b> already exists",
                    'info': f"you can visit <a href={reverse('pedia:wiki', kwargs={'title':title})}>{title}</a>"
                    },
                    status=404)
        else:
            return render(request, "encyclopedia/new.html", {'form': form})

    return render(request, "encyclopedia/new.html", {'form': EditPageForm()})

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}



  <div class="row">
    <div class="col-10 p-3">
      <form action="{% url 'pedia:edit' title %}">
        {% csrf_token %}
        {{ form.info_form }}
        <div class="form-row">
          <div class="form-group col-md-10">
            <div class="form-group">
              <label for="title_form" class="col-sm-2 col-form-label">Title:</label>
              <div class="col-sm-4">
                {% if title %}
                  <input type="text" class="form-control font-weight-bold" id="title_form" name="title_form" value="{{ title }}" disabled>
                {% else %}
                  <input type="text" class="form-control font-weight-bold" id="title_form" name="title_form">
                {% endif %}
              </div>
            </div>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-12">
            <label for="info_form" class="col-sm-2 col-form-label" >Article:</label>
            <div class="form-group pl-3">
              <textarea class="form-control" id="info_form" name="info_form">
                {{ info_md }}
              </textarea>
            </div>
          </div>
        </div>

        <div class="row justify-content-end">
          <div class="col-md-2 col-sm-6">
            <button type="submit" class="btn btn-lightblue border w-100">Save page</button>
          </div>
        </div>

      </form>
    </div>

    <!--<div class="col-2 pt-4">-->
    <!--  <a href="{% url 'pedia:edit' title %}">edit page</a>-->
    <!--</div>-->
  </div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="col-3 pt-5">
      <div class="alert alert-danger" role="alert">
          {{ message | safe}}
      </div>

      <p>
        {{ info | safe }}
      </p>
    </div>






{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'pedia:wiki' entry %}">{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2><a href='\' id="h2_wiki">Wiki</a></h2>
                <form action="{% url 'pedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" value="{{ search_query }}">
                </form>
                <div>
                    <a href="{% url 'pedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'pedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'pedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create page
{% endblock %}

{% block body %}



  <div class="row">
    <div class="col-10 p-3">
      <form action="{% url 'pedia:new' %}" method="post">
        {% csrf_token %}

        <div class="form-row">
          <div class="form-group col-md-10">
            <div class="form-group">
              <label for="title_form" class="col-sm-2 col-form-label">Title:</label>
              <div class="col-sm-4">
                {{ form.title_form }}
              </div>
            </div>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-12">
            <label for="info_form" class="col-sm-2 col-form-label" >Article:</label>
            <div class="form-group pl-3">
              {{ form.info_form }}
            </div>
          </div>
        </div>

        <div class="row justify-content-end">
          <div class="col-md-2 col-sm-6">
            <button type="submit" class="btn btn-lightblue border w-100">Create page</button>
          </div>
        </div>

      </form>
    </div>

  </div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search result
{% endblock %}

{% block body %}
    <h1>
        Search result:
    </h1>

    <ul>
        {% for result in results %}
            <li><a href="{% url 'pedia:wiki' result %}">{{ result }}</li>
        {% empty %}
            <br>
            <h5>
                Nothing found :(
            </h5>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="row p-3">
      <div class="col-10">
          {{ info | safe}}
      </div>
      <div class="col-2 pt-4">
        <a href="{% url 'pedia:edit' title %}">edit page</a>
      </div>
    </div>



{% endblock %}